// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHlUkTib1-rGwFPjxLT6qi8IKtuLUIGEA',
    appId: '1:794522024584:web:3fe30c072d694bf86d7d3d',
    messagingSenderId: '794522024584',
    projectId: 'fashion-app-70ccf',
    authDomain: 'fashion-app-70ccf.firebaseapp.com',
    storageBucket: 'fashion-app-70ccf.firebasestorage.app',
    measurementId: 'G-4BM7YMZK9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEu1rnnMA9JYfw-Zc_4mG8sdocyYlE7mA',
    appId: '1:794522024584:android:cebc63175edf50506d7d3d',
    messagingSenderId: '794522024584',
    projectId: 'fashion-app-70ccf',
    storageBucket: 'fashion-app-70ccf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJh10JOBP_BxoKOlzUuUPyX63_Ryeg7R0',
    appId: '1:794522024584:ios:8bcbf1c20cef455b6d7d3d',
    messagingSenderId: '794522024584',
    projectId: 'fashion-app-70ccf',
    storageBucket: 'fashion-app-70ccf.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJh10JOBP_BxoKOlzUuUPyX63_Ryeg7R0',
    appId: '1:794522024584:ios:8bcbf1c20cef455b6d7d3d',
    messagingSenderId: '794522024584',
    projectId: 'fashion-app-70ccf',
    storageBucket: 'fashion-app-70ccf.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHlUkTib1-rGwFPjxLT6qi8IKtuLUIGEA',
    appId: '1:794522024584:web:662f4738ceaec71e6d7d3d',
    messagingSenderId: '794522024584',
    projectId: 'fashion-app-70ccf',
    authDomain: 'fashion-app-70ccf.firebaseapp.com',
    storageBucket: 'fashion-app-70ccf.firebasestorage.app',
    measurementId: 'G-35EYKLGFTW',
  );
}
